### ISSUE TITLE
Soporte para firmar XML

### ISSUE THREAD

**Issue by Alexandr9618** [project-openubl/xbuilder#10]
Buenas deseo realizar la firma del xml pero como puedo llevarlo acabo en la documentación no me quedo muy claro quisiera ayuda. mi WSP +51 921816234

**Comment by carlosthe19916** [comment]
Hola @Alexandr9618. Acá tienes un ejemplo de como firmar un xml https://github.com/project-openubl/xbuilder/blob/master/src/test/java/io/github/project/openubl/xmlbuilderlib/xml/XMLSignerTest.java#L50 este ejemplo sigue exactamente los pasos descritos en la documentación https://project-openubl.github.io/xbuilder-docs/docs/sign_xml... Me avisas si pudiste hacerlo funcionar.
